export default {
  FILE_UPLOADED_SUCCESSFULY: "FILE_UPLOADED_SUCCESSFULY",
  FILE_UPLOAD_FAILED: "FILE_UPLOAD_FAILED",
  SAVE_LOCATION_DATA: "SAVE_LOCATION_DATA",
  SAVE_SEARCH_RESULTS: "SAVE_SEARCH_RESULTS",
};
